spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RupeshPant16/smartshop-config-repo.git
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          search-paths: .
          clone-on-start: true

server:
  port: 8888
